---
- name: Configure interfaces on Cisco routers
  hosts: routers
  gather_facts: no
  vars_files:
    - devices_vars.yml
  tasks:
    - name: Ensure the router's SSH key is in known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H -t ed25519 {{ ansible_host }}') }}"
        path: /var/lib/jenkins/.ssh/known_hosts

    - name: Configure interface settings
      cisco.iosxr.iosxr_config:
        lines:
          - description {{ lookup('vars', inventory_hostname)['description'] }}
          - ip address {{ lookup('vars', inventory_hostname)['ip_address'] }} {{ lookup('vars', inventory_hostname)['netmask'] }}
        parents: interface {{ lookup('vars', inventory_hostname)['interface'] }}
      register: config_output

    - name: Show output from configuration task
      debug:
        var: config_output

