---
- name: Configure OSPF on Cisco IOS XR routers
  hosts: routers
  gather_facts: no
  vars_files:
    - devices_ospf_vars.yml

  tasks:
    - name: Render OSPF configuration from template
      template:
        src: ospf_template.jinja
        dest: "/tmp/ospf_config_{{ inventory_hostname }}.txt"

    - name: Apply OSPF configuration
      iosxr_config:
        src: "/tmp/ospf_config_{{ inventory_hostname }}.txt"
        replace: line

