---
- name: Configure ospf on Cisco XR routers
  hosts: routers
  gather_facts: no
  vars_files:
    - devices_ospf_vars.yml
  tasks:
    - name: Ensure the router's SSH key is in known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H -t ed25519 {{ ansible_host }}') }}"
        path: /var/lib/jenkins/.ssh/known_hosts

    - name: Configure ospf settings
      cisco.iosxr.iosxr_ospf_interfaces:
        config:
          - name: "{{ hostvars[inventory_hostname]['interface'] }}"
            type: gigabitethernet
            address_family:
              - afi: "{{ hostvars[inventory_hostname]['afi'] }}"
                processes:
                  - process_id: "{{ hostvars[inventory_hostname]['process_id'] }}"
                    area:
                      area_id: "{{ hostvars[inventory_hostname]['area_id'] }}"
                cost: "{{ hostvars[inventory_hostname]['cost'] }}"
                authentication:
                  message_digest:
                    keychain: "{{ hostvars[inventory_hostname]['keychain'] }}"
        state: merged

