---
- name: Configure ospf on Cisco XR routers
  hosts: routers
  gather_facts: no
  vars_files:
    - devices_ospf_vars.yml
  tasks:
    - name: Ensure the router's SSH key is in known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H -t ed25519 {{ ansible_host }}') }}"
        path: /var/lib/jenkins/.ssh/known_hosts

    - name: Set router-specific facts
      set_fact:
        router_id: "{{ hostvars[inventory_hostname]['router_id'] }}"
        interfaces: "{{ hostvars[inventory_hostname]['interfaces'] }}"

    - name: Debug router-specific facts
      debug:
        msg: "Router ID: {{ router_id }} - Interfaces: {{ interfaces }}"

    - name: Configure ospf settings
      cisco.iosxr.iosxr_ospf_interfaces:
        config:
          - name: "{{ item.interface }}"
            type: gigabitethernet
            address_family:
              - afi: "{{ item.afi }}"
                processes:
                  - process_id: "{{ item.process_id }}"
                    area:
                      area_id: "{{ item.area_id }}"
                cost: "{{ item.cost }}"
                authentication:
                  message_digest:
                    keychain: "{{ item.keychain }}"
            state: merged
      loop: "{{ interfaces }}"
      register: config_output

    - name: Show output from configuration task
      debug:
        var: config_output

